name: BIOMI-RPI-KERNEL-BUILDER

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        description: "Raspberry Pi kernel version (ex: rpi-6.1.y)"
        required: true

env:
  IMAGE_NAME: ghcr.io/prismprotocolhub/biomi-rpi-kernel-builder

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space on GitHub runner
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          build-args: |
            KERNEL_BRANCH=${{ inputs.kernel_version }}
          platforms: |
            linux/arm64
          tags: |
            ghcr.io/prismprotocolhub/biomi-rpi-kernel-builder:${{ inputs.kernel_version }}
            ghcr.io/prismprotocolhub/biomi-rpi-kernel-builder:${{ github.sha }}

      - name: Extract Kernel Image
        run: |
          docker create --name kernel-builder ghcr.io/prismprotocolhub/biomi-rpi-kernel-builder:${{ github.sha }} /bin/bash
          docker cp kernel-builder:/build/kernel.img kernel.img
          docker rm kernel-builder

      - name: Create Release and Upload Artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: kernel.img
          tag: ${{ inputs.kernel_version }}
          name: Release Kernel ${{ inputs.kernel_version }}
          token: ${{ secrets.GITHUB_TOKEN }}